steps:
  # 1. Build the container image using Dockerfile
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-t'
      - 'us-west1-docker.pkg.dev/$PROJECT_ID/soundboard-repo/soundboard-app-auth:$COMMIT_SHA'
      - '-t'
      - 'us-west1-docker.pkg.dev/$PROJECT_ID/soundboard-repo/soundboard-app-auth:latest'
      - '.'

  # 2. Push image to Google Artifact Registry
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - 'us-west1-docker.pkg.dev/$PROJECT_ID/soundboard-repo/soundboard-app-auth:$COMMIT_SHA'

  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - 'us-west1-docker.pkg.dev/$PROJECT_ID/soundboard-repo/soundboard-app-auth:latest'

images:
  - 'us-west1-docker.pkg.dev/$PROJECT_ID/soundboard-repo/soundboard-app-auth:$COMMIT_SHA'
  - 'us-west1-docker.pkg.dev/$PROJECT_ID/soundboard-repo/soundboard-app-auth:latest'

options:
  logging: CLOUD_LOGGING_ONLY
